### TODO
# Run chsh -s $(which zsh) to set zsh as the default shell. Needs to be run as user.

- name: System Configuration | shell | zsh | install
  ansible.builtin.package:
    name:
      - zsh
    state: present

- name: System Configuration | shell | zsh | Set zsh as default shell for user
  tags: always
  ansible.builtin.user:
    name: "{{ user.name }}"
    shell: /usr/bin/zsh
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: System Configuration | shell | zsh | Copy .zshrc config file
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
    src: config_files/.zshrc
    dest: /home/{{ user.name }}/.zshrc
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: System Configuration | shell | zsh | Clone powerlevel10k git repo
  become_user: "{{ user.name }}"
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: /home/{{ user.name }}/portableapps/powerlevel10k/
    clone: yes
    depth: 1
    update: no
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: System Configuration | shell | zsh | Add powerlevel10k to .zshrc
  become_user: "{{ user.name }}"
  ansible.builtin.lineinfile:
    path: /home/{{ user.name }}/.zshrc
    line: source /home/{{ user.name }}/portableapps/powerlevel10k/powerlevel10k.zsh-theme
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: System Configuration | shell | zsh | Copy .p10k.zsh config file
  become_user: "{{ user.name }}"
  ansible.builtin.copy:
    src: config_files/.p10k.zsh
    dest: /home/{{ user.name }}/.p10k.zsh
  loop: "{{ users }}"
  loop_control:
    loop_var: user