# System configuration | ssh
ssh_users: "ansibleadmin chris"
ssh_template_file: sshd_config_ubuntu.j2

# System configuration | Dependencies
dependencies_general: true
dependencies_appimage: true
dependencies_flatpak: true
dependencies_snap: true
dependencies_homebrew: false

# System configuration | fonts
font_meslolgs_nf: true

# System Configuration | Languages and localization
lang_japanese: true

# System configuration | themes and visuals
theme_icon_candy_icons: true
theme_icon_numix_circle: true
theme_icon_papirus: true
theme_shell_nordic_darker: true
theme_shell_sweet: false
theme_copy_archives: false

# Favorite apps
firefox_flatpak: true
libreoffice: true
alacritty: false
terminator: false

# System Configuration | shell | zsh
zsh: true

# Desktop Environment
desktop_environment: "gnome"
de_gnome_blurmyshell: true
de_gnome_dashtodock: true
de_gnome_extensions: true
de_gnome_favorite_apps: true
de_gnome_set_themes: false
de_gnome_wallpaper_download: true
de_gnome_wallpaper_set: false

# Desktop Environment | gnome | software installation
gnomeextensions: true
gnomeextensions_flatpak: false

# General Software
alacarte: false
anki_flatpak: true
anki_tarball: false
base_packages: true
bottles_flatpak: true
calibre_flatpak: true
chromium_flatpak: true
clamtk_flatpak: true
dconfeditor: true
discord_flatpak: true
dropbox: false
etcher_appimage: true
ffmpeg: true
flatseal_flatpak: true
gimp_flatpak: false
org.bluesabre.MenuLibre: true
nextcloudclient_flatpak: false
syncthinggtk_flatpak: true
vlc_flatpak: true
winehq_apt_ubuntu2110: false

# Software | Productivity
ao_snap: false
flameshot_flatpak: true
joplin_flatpak: true
tusk_snap: false

# Remove unwanted software
remove_firefox_snap: true

# Software | Development
git: true
godotmono: false
imagemagick: false
inkscape: false
krita: false
monosdk: false
powershell_snap: false
renpy: false
twine_flatpak: true
twine_tarball: false
unityhub_flatpak: false
vscode: false
vscode_flatpak: true

# Development Software - hashicorp_software.yml
packer: true
terraform: true

# Gaming software
duckstation_flatpak: true
heroicgameslauncher_flatpak: true
lutris: false
minigalaxy_flatpak: false
pcsx2_flatpak: true
protonupqt_flatpak: true
retroarch_flatpak: true
steam: true
steamrommanager_appimage: true