- name: System Setup | DE | Gnome | Dash to Panel | Set dot-style-focused as Metro
  become_user: "{{ user.name }}"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/dot-style-focused"
    value: "'METRO'"
  loop: "{{ users }}"
  loop_control:
    loop_var: user

- name: System Setup | DE | Gnome | Dash to Panel | Set dot-style-unfocused as DOTS
  become_user: "{{ user.name }}"
  community.general.dconf:
    key: "/org/gnome/shell/extensions/dash-to-panel/dot-style-unfocused"
    value: "'DOTS'"
  loop: "{{ users }}"
  loop_control:
    loop_var: user

